BINANCE_API_KEY = "YOUR_BINANCE_API_KEY"
BINANCE_SECRET_KEY = "YOUR_BINANCE_SECRET_KEY"
DB_HOST = "YOUR_DB_HOST"
DB_USER = "YOUR_DB_USER"
DB_PASSWORD = "YOUR_DB_PASSWORD"
DATABASE = "YOUR_DATABASE"
DB_PORT = 3306
GOOGLE_NEWS_API_KEY = "YOUR_GOOGLE_NEWS_API_KEY"
